services:
  - type: web
    name: video-converter
    env: node
    plan: free
    buildCommand: cd video-converter && npm install
    startCommand: node server.js
    rootDir: video-converter
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
