services:
  - type: web
    name: video-converter
    env: node
    plan: free
    rootDir: video-converter
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
