services:
  - type: web
    name: video-converter
    rootDir: video-converter
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: SUPABASE_URL
        sync: true
      - key: SUPABASE_KEY
        sync: true
